### ISSUE TITLE
Segmentation fault during forward solve with CUDA

### ISSUE THREAD

**Issue by sebastiangrimberg** [pghysels/STRUMPACK#107]
Running with 1 MPI process and 1 OpenMP thread, when I set `enable_gpu`, I am getting a segmentation fault as soon as I call `solve` for the first time after factoring a matrix. The log output from the factorization looks fine, and matches exactly what I get with `disable_gpu`. I'm using no compression and the default reordering. This is STRUMPACK's `main` commit cb3d84950a160c8d60685fa5efffe443635f3308, built with GCC 12.3, OpenMPI 4.1.5, CUDA 12, OpenMP, MAGMA, and SLATE. I'm wondering if I might be using something incorrectly, or maybe it's not recommended to use MAGMA + STRUMPACK?

Backtrace from `gdb`:

```
Thread 1 "palace-x86_64.b" received signal SIGSEGV, Segmentation fault.
0x00007fffb7d80ac3 in mkl_lapack.dgetrs_ () from /apps/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_gf_lp64.so.2
(gdb) bt
#0  0x00007fffb7d80ac3 in mkl_lapack.dgetrs_ () from /apps/intel/oneapi/mkl/2023.1.0/lib/intel64/libmkl_gf_lp64.so.2
#1  0x00007fffd41ce475 in strumpack::blas::getrs (t=<optimized out>, n=<optimized out>, n@entry=1, nrhs=<optimized out>, nrhs@entry=2,
    a=a@entry=0x7ffe8cec7b80, lda=<optimized out>, lda@entry=1, ipiv=<optimized out>, b=0x31cfca50, ldb=<optimized out>)
    at /build/extern/STRUMPACK/src/dense/BLASLAPACKWrapper.cpp:1562
#2  0x00007fffd41dedf3 in strumpack::getrs_omp_task<double> (t=t@entry=78 'N', m=1, n=2, a=0x7ffe8cec7b80, lda=1, piv=<optimized out>,
    b=0x31cfca50, ldb=131059, depth=0)
    at /build/extern/STRUMPACK/src/dense/BLASLAPACKOpenMPTask.cpp:535
#3  0x00007fffd41f49be in strumpack::DenseMatrix<double>::solve_LU_in_place (this=this@entry=0x25ff0038, b=..., piv=<optimized out>,
    depth=depth@entry=0) at /build/extern/STRUMPACK/src/dense/DenseMatrix.cpp:650
#4  0x00007fffd40736b6 in strumpack::FrontalMatrixMAGMA<double, long long>::fwd_solve_phase2 (this=0x25feffe0, b=..., bupd=...,
    etree_level=<optimized out>, task_depth=0)
    at /build/extern/STRUMPACK/src/sparse/fronts/FrontalMatrixMAGMA.cpp:798
#5  0x00007fffd3ed43ce in strumpack::FrontalMatrix<double, long long>::forward_multifrontal_solve (this=0x25feffe0, b=...,
    work=0x201ff198, etree_level=13, task_depth=0)
    at /build/extern/STRUMPACK/src/sparse/fronts/FrontalMatrix.cpp:231
#6  0x00007fffd3ed4146 in strumpack::FrontalMatrix<double, long long>::fwd_solve_phase1 (this=this@entry=0x25fef8b0, b=..., bupd=...,
    work=work@entry=0x201ff170, etree_level=etree_level@entry=12, task_depth=task_depth@entry=0)
    at /build/extern/STRUMPACK/src/sparse/fronts/FrontalMatrix.cpp:249
#7  0x00007fffd3ed431b in strumpack::FrontalMatrix<double, long long>::_ZNK9strumpack13FrontalMatrixIdxE26forward_multifrontal_solveERNS_11DenseMatrixIdEEPS3_ii._omp_fn.0(void) ()
    at /build/extern/STRUMPACK/src/sparse/fronts/FrontalMatrix.cpp:237
#8  0x00007fffb15d55e6 in GOMP_parallel (
    fn=0x7fffd3ed42d6 <strumpack::FrontalMatrix<double, long long>::_ZNK9strumpack13FrontalMatrixIdxE26forward_multifrontal_solveERNS_11DenseMatrixIdEEPS3_ii._omp_fn.0(void)>, data=0x7fffffff81b0, num_threads=1, flags=0) at ../../../gcc-releases-gcc-12.3.0/libgomp/parallel.c:178
#9  0x00007fffd3ed43b2 in strumpack::FrontalMatrix<double, long long>::forward_multifrontal_solve (this=0x25fef8b0, b=...,
    work=0x201ff170, etree_level=12, task_depth=0)
    at /build/extern/STRUMPACK/src/sparse/fronts/FrontalMatrix.cpp:231
```

**Comment by sebastiangrimberg** [comment]
Ah, indeed building STRUMPACK without MAGMA seems to resolve the issue.

**Comment by pghysels** [comment]
I'm trying to fix the MAGMA code.
Thanks for reporting this.

**Comment by pghysels** [comment]
I think it's fixed in the latest commit.

Now, when running with MAGMA, and the factorization fits on the GPU, the triangular solve is done on the GPU.
But the solve is only done on GPU when running with a single MPI rank (for more MPI ranks I cannot properly estimate how much device memory will be needed so the  factors are copied back to the host, and the solve is done on the CPU).

Without MAGMA the solve is always done on CPU.

**Comment by sebastiangrimberg** [comment]
That fixed it! Thanks for the quick response.
