### ISSUE TITLE
An error occurred running test_HSS_seq in strumpack-3.1.1

### ISSUE THREAD

**Issue by jiaruipeng** [pghysels/STRUMPACK#16]
Using./test_HSS_seq command run shows the following error:
——————————————————————————————————
# Running with:
# OMP_NUM_THREADS=4 ./test_HSS_seq T 1000 
# tol = 0.01
# created H matrix of dimension 1000 x 1000 with 4 levels
# compression succeeded!
# rank(H) = 9
# memory(H) = 1.135 MB, 14.1875% of dense
# relative error = ||A-H*I||_F/||A||_F = 0.0041072
# absolute error = ||A-H*I||_F = 0.195952
# relative error = ||H0*B0-A0*B0||_F/||A0*B0||_F = 0.000820075
# relative error = ||H0'*B0-A0'*B0||_F/||A0'*B0||_F = 0.000820075
# relative error = ||H1*B1-A1*B1||_F/||A1*B1||_F = 0.000979003
# relative error = ||H1'*B1-A1'*B1||_F/||A1'*B1||_F = 0.000979003
# extracting individual elements, avg error = 7.53244e-05
Segmentation fault (core dumped)
————————————————————————————————————
When looking for errors, it was found that there was an error in the【 laswp() 】function，
Can you give me some Suggestions or examples to solve this problem?
thanks.

**Comment by pghysels** [comment]
Hi jiaruipeng,

I cannot reproduce your problem here on my machine. It would help if you can tell us what version of STRUMPACK you are using, which OS, which compiler and BLAS/LAPACK version. Then we can try to reproduce the problem and then debug it.

Did you look for errors using gdb or something like that? Is it possible to give the stack trace? So I can see where this laswp function is being called.

Pieter

**Comment by jiaruipeng** [comment]
Hi Pieter

The STRUMPACK version I used was version 3.1.1.
OS---Linux.
The compiler version I used was  gcc 7.3.
The MPI complier version was Inter 15.
The BLAS/LAPACK I used was MKL Inter 15.
 Yes , I used gdb to look for errors,

Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
* Running with:
* OMP_NUM_THREADS=4 /home/ganggang/STRUMPACK-master/build/test/test_HSS_seq T 1000 
[New Thread 0x7ffff26c0700 (LWP 3924)]
[New Thread 0x7ffff1ebf700 (LWP 3925)]
[New Thread 0x7ffff16be700 (LWP 3926)]
* tol = 0.01
* created H matrix of dimension 1000 x 1000 with 4 levels
* compression succeeded!
* rank(H) = 9
* memory(H) = 1.135 MB, 14.1875% of dense
* relative error = ||A-H*I||_F/||A||_F = 0.0041072
* absolute error = ||A-H*I||_F = 0.195952
* relative error = ||H0*B0-A0*B0||_F/||A0*B0||_F = 0.000820075
* relative error = ||H0'*B0-A0'*B0||_F/||A0'*B0||_F = 0.000820075
* relative error = ||H1*B1-A1*B1||_F/||A1*B1||_F = 0.000979003
* relative error = ||H1'*B1-A1'*B1||_F/||A1'*B1||_F = 0.000979003
* extracting individual elements, avg error = 7.53244e-05

Thread 1 "test_HSS_seq" received signal SIGSEGV, Segmentation fault.
0x00007ffff6b45d0a in dlaswp_ ()
   from /opt/intel/composer_xe_2015.0.090/mkl/lib/intel64/libmkl_intel_lp64.so
(gdb) bt
_#0  0x00007ffff6b45d0a in dlaswp_ ()
   from /opt/intel/composer_xe_2015.0.090/mkl/lib/intel64/libmkl_intel_lp64.so
_#1  0x0000000000425be2 in strumpack::HSS::HSSBasisID<double>::dense() const ()
_#2  0x000000000044078d in strumpack::HSS::HSSMatrix<double>::extract_bwd_internal(strumpack::HSS::WorkExtract<double>&, int) const ()
_#3  0x0000000000441143 in strumpack::HSS::HSSMatrix<double>::extract_bwd(strumpack::DenseMatrix<double>&, strumpack::HSS::WorkExtract<double>&, int) const ()
_#4  0x00007ffff3f6fa6f in GOMP_parallel (
    fn=0x419770 <strumpack::HSS::HSSMatrix<double>::extract_add(std::vector<unsigned long, std::allocator<unsigned long> > const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, strumpack::DenseMatrix<double>&) const [clone ._omp_fn.104]>, data=0x7fffffffcfd0, num_threads=1, flags=0)
    at ../.././libgomp/parallel.c:168
_#5  0x000000000042a19e in strumpack::HSS::HSSMatrix<double>::extract_add(std::vector<unsigned long, std::allocator<unsigned long> > 

Thanks
Jiaruipeng

**Comment by pghysels** [comment]
Hi Jiaruipeng,
I believe the problem is that the laswp function (implemented in intel MKL) is being called on a matrix with 0 columns. That shouldn't be a problem, but perhaps it's an MKL 2015 issue.
I have not been able to rerun with MKL 2015. The machines I have access to here have 2018 and 2019 and that runs fine.
But I have pushed a fix: https://github.com/pghysels/STRUMPACK/commit/2d636b1d2c59b0b003f70fa4914a9232603ff0c1

Perhaps you can try the master branch with this latest fix.
Thank you for reporting this.

Pieter

**Comment by jiaruipeng** [comment]
Hi Pieter,
Sorry for the late reply.
I have been debugging these days in case of other problems.I have successfully compiled the program after using your modified program. 
Thank you very much.

Jiaruipeng
